background {
    monitor =
    path = /home/thomas/.config/hypr/lockscreen.jpg
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    outer_color = rgb(255, 255, 255)
    inner_color = rgb(0, 0, 0)
    font_color = rgb(255, 255, 255)
    placeholder_text = Passwort
    position = 0, 0
    halign = center
    valign = center
}
